spring:
  data:
    redis:
      host: ${REDIS_HOST}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      port: 15997
      connect-timeout: 3000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
      ssl:
        enabled: false


  config:
    import: optional:file:.env[.properties]
  application:
    name: QuizIt
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${GOOGLE_CLIENT_REDIRECT}
            client-id: ${GOOGLE_CLIENT_ID:test-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:test-client-server}
            scope:
              - email
              - profile
              - openid
              - https://www.googleapis.com/auth/forms.body.readonly
              - https://www.googleapis.com/auth/drive.readonly


  datasource:
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 10000
      max-lifetime: 25000
      connection-timeout: 20000
    url: ${DB_URL}
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jvm:
    arguments: --add-opens=java.base/sun.misc=ALL-UNNAMED
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVICE_EMAIL}
    password: ${EMAIL_SERVICE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
server:
  port: ${PORT:8080}
  address: 0.0.0.0
# JVM args (NOTE: ths is usually NOT read from application.yml)

# ===============================
# JWT lity Configuration
# ===============================

security:
  jwt:
    # 🔐 SECRET (from environment variable)
    secret: ${JWT_SECRET}

    # Non-secret identifiers
    issuer: ${JWT_ISSUER}

    # Token validity (seconds)
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS}

    # Cookie configuration
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME}

    cookie-secure: ${JWT_COOKIE_SECURE}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY}
    cookie-domain: ${JWT_COOKIE_DOMAIN}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE}

  encryption:
    google-token-secret: ${GOOGLE_TOKEN_SECRET}


# ===============================
# OAuth
# ===============================



app:
  auth:
    frontend:
      base-url: ${VITE_REACT_BASE_URL:http://localhost:5173}
      success-path: /oauth2/login/success
      admin-review-path: /admin/teachers


# ===============================
# GROQ
# ===============================

groq:
  api:
    key: ${GROQ_API_KEY}
    url: https://api.groq.com/openai/v1/chat/completions
